### ISSUE TITLE
`meltano invoke meltano-map-transformer --about` fails with unhelpful error message

### ISSUE THREAD

**Issue by astrojuanlu** [MeltanoLabs/meltano-map-transform#17]
To reproduce:

```
meltano init meltano
cd meltano
meltano add mapper meltano-map-transformer
meltano invoke meltano-map-transformer --help  # Works!
meltano invoke meltano-map-transformer --about  # Fails
```

Error:

```
$ meltano invoke meltano-map-transformer --about
2022-05-05T12:07:28.231880Z [info     ] Environment 'dev' is active
time=2022-05-05 14:07:29 name=meltano-map-transformer level=INFO message=meltano-map-transformer v[could not be detected], Meltano SDK v0.4.2)
Traceback (most recent call last):
  File "/tmp/meltano_tests/meltano/.meltano/mappers/meltano-map-transformer/venv/bin/meltano-map-transform", line 8, in <module>
    sys.exit(StreamTransform.cli())
  File "/tmp/meltano_tests/meltano/.meltano/mappers/meltano-map-transformer/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/meltano_tests/meltano/.meltano/mappers/meltano-map-transformer/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/tmp/meltano_tests/meltano/.meltano/mappers/meltano-map-transformer/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/meltano_tests/meltano/.meltano/mappers/meltano-map-transformer/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/meltano_tests/meltano/.meltano/mappers/meltano-map-transformer/venv/lib/python3.9/site-packages/singer_sdk/mapper_base.py", line 140, in cli
    config_dict = merge_config_sources(
  File "/tmp/meltano_tests/meltano/.meltano/mappers/meltano-map-transformer/venv/lib/python3.9/site-packages/singer_sdk/configuration/_dict_config.py", line 83, in merge_config_sources
    config.update(read_json_file(config_path))
TypeError: 'NoneType' object is not iterable
```

**Comment by astrojuanlu** [comment]
Notice that calling the binary directly works:

```
$ ./.meltano/mappers/meltano-map-transformer/venv/bin/meltano-map-transform --help
Usage: meltano-map-transform [OPTIONS]

  Execute the Singer mapper.

Options:
  --input FILENAME          A path to read messages from instead of from
                            standard in.
  --config TEXT             Configuration file location or 'ENV' to use
                            environment variables.
  --format [json|markdown]  Specify output style for --about
  --about                   Display package metadata and settings.
  --version                 Display the package version.
  --help                    Show this message and exit.
$ ./.meltano/mappers/meltano-map-transformer/venv/bin/meltano-map-transform --about
time=2022-05-05 14:12:18 name=meltano-map-transformer level=INFO message=meltano-map-transformer v[could not be detected], Meltano SDK v0.4.2)
time=2022-05-05 14:12:18 name=meltano-map-transformer level=INFO message=Skipping parse of env var settings...
time=2022-05-05 14:12:18 name=meltano-map-transformer level=WARNING message=Config validation failed: 'stream_maps' is a required property
JSONSchema was: {'type': 'object', 'properties': {'stream_maps': {'type': 'object', 'properties': {}, 'additionalProperties': {'type': ['object', 'string', 'null'], 'properties': {'__filter__': {'type': ['string', 'null']}, '__source__': {'type': ['string', 'null']}, '__else__': {'type': ['null']}, '__key_properties__': {'type': ['array', 'null'], 'items': {'type': 'string'}}}, 'additionalProperties': {'type': ['string', 'null']}}, 'description': 'Stream maps'}, 'stream_map_config': {'type': ['object', 'null'], 'properties': {}, 'description': 'User-defined config values to be used within map expressions.'}}, 'required': ['stream_maps']}
time=2022-05-05 14:12:18 name=root level=INFO message=Operator '__else__=None' was not found. Unmapped streams will be included in output.
Name: meltano-map-transformer
Description: A map transformer which implements the Stream Maps capability.
Version: [could not be detected]
Sdk_Version: 0.4.2
Capabilities: [stream-maps]
Settings: {'type': 'object', 'properties': {'stream_maps': {'type': 'object', 'properties': {}, 'additionalProperties': {'type': ['object', 'string', 'null'], 'properties': {'__filter__': {'type': ['string', 'null']}, '__source__': {'type': ['string', 'null']}, '__else__': {'type': ['null']}, '__key_properties__': {'type': ['array', 'null'], 'items': {'type': 'string'}}}, 'additionalProperties': {'type': ['string', 'null']}}, 'description': 'Stream maps'}, 'stream_map_config': {'type': ['object', 'null'], 'properties': {}, 'description': 'User-defined config values to be used within map expressions.'}}, 'required': ['stream_maps']}
```

**Comment by astrojuanlu** [comment]
The culprit seems to be here:

https://gitlab.com/meltano/meltano/-/blob/80498c3e/src/meltano/core/plugin/singer/mapper.py#L52-67

If no `mappings` are found, then the mapping config is just empty and that gets dumped to the file. On the other hand, it looks like an extra `mapping_name` property is also needed.

I don't understand how is this supposed to work but at least I have a workaround now. This issue probably belongs to https://gitlab.com/meltano/meltano/ rather than here, so I'm closing for now.
